function importS1 = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  IMPORTS1 = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the numeric
%  data.
%
%  IMPORTS1 = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  IMPORTS1 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  importS1 = importfile("C:\Users\cheta\CHETAN\STUDY\MATLAB\R2021\Tutorial_Videos\import.xlsx", "Sheet2", [2, 4]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-Dec-2024 16:13:29

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 4];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":C" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["p", "q", "r"];
opts.VariableTypes = ["double", "double", "double"];

% Import the data
importS1 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":C" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    importS1 = [importS1; tb]; %#ok<AGROW>
end

%% Convert to output type
importS1 = table2array(importS1);
end